# Generated by Django 3.1 on 2020-12-01 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabrics', '0003_auto_20201026_2041'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCalculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemistry_type', models.CharField(choices=[('EVO', 'EVO (non-fluorinated)'), ('NORR', 'NORR (fluorinated)')], max_length=8)),
                ('dry_weight', models.FloatField()),
                ('wet_weight', models.FloatField()),
                ('minimum_bath', models.IntegerField()),
                ('finishing_temperature', models.IntegerField()),
                ('finishing_speed', models.IntegerField()),
                ('tenter_frame_length', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrics.fabric')),
                ('linked_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
