# Generated by Django 3.1 on 2020-12-16 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecalculator',
            name='minimum_bath',
        ),
    ]
