# Generated by Django 3.1 on 2020-12-30 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_calculator', '0002_remove_recipecalculator_minimum_bath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecalculator',
            name='dry_weight',
        ),
        migrations.RemoveField(
            model_name='recipecalculator',
            name='wet_weight',
        ),
    ]
