# Generated by Django 3.1 on 2021-01-28 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_names', '0001_initial'),
        ('recipe_concentrations', '0002_remove_recipeconcentration_percent_total'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_recipe_concentration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe_concentrations.recipeconcentration'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_recipe_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe_names.recipename'),
        ),
    ]
