# Generated by Django 3.1 on 2020-10-30 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe_names', '0001_initial'),
        ('recipe_concentrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fabrics', '0003_auto_20201026_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_length_unit', models.CharField(choices=[('YD', 'yards(Yds)'), ('M', 'meters(m)')], default='YD', max_length=4)),
                ('wet_pick_up_percent', models.FloatField(default=60.0)),
                ('curing_specs_known', models.BooleanField(choices=[(True, 'Yes, I will enter it below'), (False, 'No, I will assume that the default values below are ok.')], default=False)),
                ('cure_temp', models.IntegerField(default=170)),
                ('cure_time', models.IntegerField(default=120)),
                ('mixing_tank_size', models.FloatField(default=100)),
                ('minimum_bath', models.FloatField(default=50)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrics.fabric')),
                ('linked_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_to_mill_procedure', to=settings.AUTH_USER_MODEL)),
                ('recipe_concentration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_concentrations.recipeconcentration')),
                ('recipe_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_names.recipename')),
            ],
        ),
    ]
