# Generated by Django 3.1 on 2020-11-12 02:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0003_auto_20201026_2041'),
        ('recipe_concentrations', '0002_remove_recipeconcentration_percent_total'),
        ('recipe_names', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mill_procedure', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductionRun',
            new_name='MillProcedure',
        ),
    ]
