# Generated by Django 3.1 on 2020-11-12 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mill_procedure', '0003_millprocedure_run_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='millprocedure',
            name='minimum_bath',
        ),
    ]
