# Generated by Django 3.1 on 2020-10-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeConcentration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_type', models.CharField(default='NORR', max_length=16)),
                ('concentration', models.CharField(max_length=16)),
                ('percent_1', models.FloatField()),
                ('percent_2', models.FloatField()),
                ('percent_3', models.FloatField()),
                ('percent_4', models.FloatField()),
                ('percent_5', models.FloatField()),
                ('percent_6', models.FloatField()),
                ('percent_total', models.FloatField(default=5.0)),
            ],
        ),
    ]
