# Generated by Django 3.1 on 2020-11-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_concentrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeconcentration',
            name='percent_total',
        ),
    ]
