# Generated by Django 3.1 on 2021-02-08 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabrics', '0004_auto_20210128_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrics.address')),
            ],
        ),
    ]
