# Generated by Django 3.1 on 2020-08-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DWR_Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name_1', models.CharField(max_length=16)),
                ('recipe_name_2', models.CharField(max_length=16)),
                ('dwr_concentration', models.FloatField()),
                ('cfl_concentration', models.FloatField()),
                ('softener_concentration', models.FloatField(default=0)),
                ('h20_concentration', models.FloatField(default=0)),
            ],
        ),
    ]
