# Generated by Django 3.1 on 2020-08-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeConcentration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_type', models.CharField(max_length=16)),
                ('concentration', models.CharField(max_length=16)),
                ('percent_1', models.FloatField()),
                ('percent_2', models.FloatField()),
                ('percent_3', models.FloatField()),
                ('percent_4', models.FloatField()),
                ('percent_5', models.FloatField()),
                ('percent_6', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.FloatField()),
                ('ref_number', models.CharField(max_length=16)),
                ('rank', models.CharField(max_length=16)),
                ('component_1', models.CharField(max_length=16)),
                ('component_2', models.CharField(max_length=16)),
                ('component_3', models.CharField(max_length=16)),
                ('component_4', models.CharField(max_length=16)),
                ('component_5', models.CharField(max_length=16)),
                ('component_6', models.CharField(max_length=16)),
                ('cost_component_1', models.FloatField()),
                ('cost_component_2', models.FloatField()),
                ('cost_component_3', models.FloatField()),
                ('cost_component_4', models.FloatField()),
                ('cost_component_5', models.FloatField()),
                ('cost_component_6', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='DWR_Recipe',
        ),
    ]
