# Generated by Django 3.1 on 2020-10-15 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompositionsInFabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_composition', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='FabricComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_composition', models.CharField(choices=[('S', 'Synthetic: Polyester, Nylon, Spandex, Acrylic or Polyolefin'), ('C', 'Cellulosic: Cotton, Linen, Flax, Bamboo, Rayon, Acetate ETC'), ('A', 'Animal: Wool, Cashmere, Alpaca')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Mill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mill_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_customer', models.CharField(max_length=32)),
                ('fabric_name', models.CharField(max_length=32)),
                ('fabric_weight', models.FloatField()),
                ('fabric_weight_unit', models.CharField(choices=[('OZYD', 'oz/yd^2 (Ounces per square yard)'), ('GSM', 'g/m^2 (GSM)')], default='GSM', max_length=8)),
                ('fabric_width', models.FloatField()),
                ('fabric_width_unit', models.CharField(choices=[('IN', 'Inches (in)'), ('CM', 'Centimeters (cm)')], default='IN', max_length=16)),
                ('end_use', models.CharField(choices=[('A', 'Apparel'), ('U', 'Upholstery'), ('M', 'Medical'), ('I', 'Industrial')], max_length=32)),
                ('fabric_construction', models.CharField(choices=[('KS', 'Knit - Smooth / Filament'), ('KB', 'Knit - Brushed / Fleeced / Hairy'), ('WF', 'Woven-Flat'), ('WB', 'Woven-Brushed / Fleeced / Decorative / Hairy'), ('U', 'Upholstery')], max_length=8)),
                ('compositions', models.ManyToManyField(related_name='fabrics_composition', through='fabrics.CompositionsInFabric', to='fabrics.FabricComposition')),
                ('mill_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrics.mill')),
            ],
        ),
        migrations.AddField(
            model_name='compositionsinfabric',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrics.fabric'),
        ),
        migrations.AddField(
            model_name='compositionsinfabric',
            name='fabric_composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrics.fabriccomposition'),
        ),
    ]
