# Generated by Django 3.1 on 2020-10-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabriccomposition',
            name='fabric_composition',
        ),
        migrations.AddField(
            model_name='fabriccomposition',
            name='composition',
            field=models.CharField(choices=[('Polyester', 'Polyester'), ('Nylon', 'Nylon'), ('Spandex', 'Spandex'), ('Acrylic', 'Acrylic'), ('Polyolefin', 'Polyolefin'), ('Sorona (PBT)', 'Sorona (PBT)'), ('Cotton', 'Cotton'), ('Linen', 'Linen'), ('Flax', 'Flax'), ('Bamboo', 'Bamboo'), ('Rayon', 'Rayon'), ('Acetate', 'Acetate'), ('Wool', 'Wool'), ('Cashmere', 'Cashmere'), ('Alpaca', 'Alpaca'), ('Unknown', 'Unknown')], default='Unknown', max_length=64),
        ),
    ]
