# Generated by Django 3.1 on 2020-10-26 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fabrics', '0002_auto_20201023_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositionsinfabric',
            name='percent_composition',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserToMill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_mill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrics.mill')),
                ('linked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mill',
            name='linked_user',
            field=models.ManyToManyField(related_name='mill_users', through='fabrics.UserToMill', to=settings.AUTH_USER_MODEL),
        ),
    ]
