# Generated by Django 3.1 on 2021-01-28 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('fabrics', '0003_auto_20201026_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address_1', models.CharField(max_length=64)),
                ('street_address_2', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('zip_code', models.CharField(max_length=32)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.country')),
            ],
        ),
        migrations.AddField(
            model_name='mill',
            name='mill_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fabrics.address'),
        ),
    ]
