# Generated by Django 3.1 on 2020-11-19 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabrics', '0003_auto_20201026_2041'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_concentrations', '0002_remove_recipeconcentration_percent_total'),
        ('recipe_names', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingCalculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_generate_recipe', models.BooleanField()),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrics.fabric')),
                ('linked_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe_concentration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_concentrations.recipeconcentration')),
                ('recipe_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_names.recipename')),
            ],
        ),
    ]
