# Generated by Django 3.1 on 2021-02-10 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_names', '0001_initial'),
        ('order', '0002_order_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('tracking_page', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='chemistry_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe_names.recipename'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(choices=[('AIR', 'Air Freight'), ('SEA', 'Sea Freight'), ('TRAIN', 'Train Freight'), ('TRUCK', 'Truck Freight')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.carrier'),
        ),
    ]
