# Generated by Django 3.1 on 2021-02-11 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_usertobrand'),
        ('order', '0003_auto_20210210_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.brand'),
        ),
    ]
