# Generated by Django 3.1 on 2021-02-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(choices=[('Air Freight', 'Air Freight'), ('Sea Freight', 'Sea Freight'), ('Train Freight', 'Train Freight'), ('Truck Freight', 'Truck Freight')], max_length=64, null=True),
        ),
    ]
