# Generated by Django 3.1 on 2021-02-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210211_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='identifier',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
