# Generated by Django 3.1 on 2021-02-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_pdf', models.BinaryField()),
            ],
        ),
    ]
