# Generated by Django 3.1 on 2021-02-17 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_usertobrand'),
        ('order', '0007_orderpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpdf',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.brand'),
        ),
        migrations.AlterField(
            model_name='orderpdf',
            name='order_pdf',
            field=models.FileField(upload_to=''),
        ),
    ]
