# Generated by Django 3.1 on 2021-02-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210217_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpdf',
            name='order_number',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
