# Generated by Django 3.1 on 2021-02-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderpdf_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpdf',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
